[package]
name = "middlybiddly"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
anyhow = "1"
http = "1"
http-body-util = "0.1.3"
spin-sdk = { version = "5.1.0", features = ["wasip3-unstable"] }
wit-bindgen = "0.46"
